[struct]
name="parameter"
namespace="app"
maxsize=32
include = ["cstdint","app.h"]
[define]
WorkMax=100

[[member]]
name="name" # member name
type="std::string"
default="OK"
[[member]]
name="age" # member's age
type="uint8_t"
default=0
[[member]]
name="height"
type="float"
default=170.5
[[member]]
name="class_type"
type="char"
default="A"
[[member]]
name="country"
type="char"
default="o"
array=4
[[member]]
name="dummy"
type="uint8_t"
[[member]]
name="progress"
type="uint16_t"
array="WorkMax"
[[member]]
name="state"
type="unsigned"
bits=3
[[member]]
name="registered"
type="unsigned"
bits=1
[[member]]
name="step"
type="unsigned"
bits=4
